In [2]:
# Latihan Data Frame

# Import package pandas terlebih dahulu
import pandas as pd

# Program
mhs = pd.DataFrame([['1', 'Informatika', 50, 30, 20], [
                   '2', 'Sistem Informasi', 55, 30, 25], ['3', 'Teknik Sipil', 40, 30, 10]])

# Membuat columns
mhs.columns = ['No', 'Prodi', 'Mahasiswa', 'Lakilaki', 'Perempuan']
mhs

No             Prodi  Mahasiswa  Lakilaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

In [4]:
# Latihan Dictionary
state = {
    "Nama": "Raihan Ashil Zaki",
    "NIM": "2020071037",
    "Prodi": "Informatika",
    "Universitas": "Universitas Pembangunan Jaya"
}
print(state)

{'Nama': 'Raihan Ashil Zaki', 'NIM': '2020071037', 'Prodi': 'Informatika', 'Universitas': 'Universitas Pembangunan Jaya'}


In [6]:
# Latihan List 
Mahasiswa = ["Raihan Ashil Zaki", "2020071037", "Informatika", "Desain dan Analisis Algoritma", "20", "UPJ"]
print(Mahasiswa) #menampilkan seluruh data yang ada pada List Mahasiswa
print(Mahasiswa[1])#Mengambil dan mencetak data NIM
print(Mahasiswa[5])#Mengambil dan mencetak nama Universitas
print(Mahasiswa[1:3])#Mengambil dan mencetak NIM dan Prodi menggunakan list slicing
# Menambahkan kata UPJ menggunakan Iterasi
for aUniv in Mahasiswa:
    print("UPJ " + aUniv)

['Raihan Ashil Zaki', '2020071037', 'Informatika', 'Desain dan Analisis Algoritma', '20', 'UPJ']
2020071037
UPJ
['2020071037', 'Informatika']
UPJ Raihan Ashil Zaki
UPJ 2020071037
UPJ Informatika
UPJ Desain dan Analisis Algoritma
UPJ 20
UPJ UPJ


In [7]:
import numpy as np


# Latihan Matrix
ourMatrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(ourMatrix)
transMatrix = np.arange(9).reshape((3, 3))
np.transpose(transMatrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [8]:
# Latihan Sets
yellow = {'dandelions', 'fire hydrant'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}
print(yellow | red)
print(yellow & red)

{'leaves', 'dandelions', 'fire hydrant', 'rose', 'blood'}
{'fire hydrant'}


In [9]:
# Latihan Tuples
UPJ = ("Universitas", "Pembangunan", "Jaya")
print(UPJ[1])  # Mengambil dan mencetak elemen dari index ke-1
# Mengambil dan mencetak elemen dari index ke-0 sampai ke-n(terakhir)
print(UPJ[0:])

# Nested tuples
Pertama = (100)
Kedua = (200, 400, 600)
Ketiga = (300)
Keempat = (400, 800)
nested_tuple = Pertama, Kedua, Ketiga, Keempat
print(nested_tuple)

Pembangunan
('Universitas', 'Pembangunan', 'Jaya')
(100, (200, 400, 600), 300, (400, 800))
